server:
  port: 8082
spring:
  datasource:
    druid:
      url: jdbc:oracle:thin:@127.0.0.1:1522:ora11g
      username: wang
      password: wang
      driver-class-name: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      enabled: true #开启上传文件
      max-file-size: 20MB #文件大小
      max-request-size: 50MB #请求大小
file:
  save-path: 'D:\报表\'
  path: 'C:\Users\Administrator\Downloads\湘人社函〔2020〕159号(一次性退休补贴申报第19页).pdf'
mybatis-plus:
  mapper-locations: classpath:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl